apiVersion: v1
kind: Service
metadata:
  labels:
    app: url-shortener
  name: url-shortener
  namespace: url-shortener
spec:
  type: NodePort
  selector:
    app: url-shortener
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30800
